spring:
  application:
    name: batch
  datasource:
    url: jdbc:postgresql://localhost:5432/batch
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
  batch:
    job:
      enabled: false # Disable the job to prevent it from running automatically while startup
    jdbc:
      initialize-schema: never